/**
 * Toast types — single source of truth for the toast/undo system.
 * Implementation lives in the Zustand store (see store/index.ts:
 * `pushToast` / `dismissToast` actions and the `toasts` slice).
 *
 * Architecture decision (2026-05-06): the store stores the `undo`
 * function reference verbatim — call sites capture their own `before`
 * snapshot in a closure. The store has no awareness of what slices an
 * undo touches. See ToastContainer for the rendering side.
 */

export type ToastVariant = 'success' | 'error' | 'info';

export interface ToastSpec {
  /** Generated by pushToast. */
  id: string;
  /** Plain user-facing text. Single-line; long messages truncate in UI. */
  message: string;
  /** Optional reverse — invoked AND dismisses on click. Caller closes
   *  over its own `before` snapshot of the touched slice(s). */
  undo?: () => void;
  /** Visual treatment. Default 'info'. */
  variant?: ToastVariant;
  /** ms before auto-dismiss. Default: 4500 with undo, 2500 without. */
  duration?: number;
}

/** Caller-supplied toast spec — pushToast generates the id internally. */
export type ToastInput = Omit<ToastSpec, 'id'>;

/** Maximum number of visible toasts. Bounds visible-stack height only;
 *  excess pushes drop the oldest visible toast (its undo closure stays
 *  reachable via the persistent Undo button, since `undoHistory` is a
 *  separate slice — see UNDO_HISTORY_MAX). */
export const TOAST_STACK_MAX = 4;

/** Maximum number of undo closures retained in `undoHistory`. Decoupled
 *  from `TOAST_STACK_MAX` so the persistent Undo button can reach back
 *  past visible toasts — closures survive auto-dismiss and only get
 *  evicted when this cap is exceeded by a newer push. */
export const UNDO_HISTORY_MAX = 20;

/** Default auto-dismiss delays. */
export const TOAST_DURATION_WITH_UNDO = 4500;
export const TOAST_DURATION_DEFAULT   = 2500;

/** One entry in the undoHistory slice. Outlives the toast that
 *  spawned it — `id` is shared so the store can dismiss the still-
 *  visible toast (if any) when the undo runs. */
export interface UndoEntry {
  /** Same id as the originating ToastSpec. */
  id: string;
  /** Same message as the toast — used for the persistent Undo button's
   *  tooltip ("Undo: Deleted ingredient"). */
  message: string;
  /** The reverse-action closure. */
  undo: () => void;
  /** Push timestamp — kept for potential future surfaces (history list,
   *  age-based eviction). Not load-bearing yet. */
  ts: number;
}
